### ISSUE TITLE
When disabling the extension, the icon tray doesn't return to the default position and behaviour

### ISSUE THREAD

**Issue by pkillnine** [phocean/TopIcons-plus#123]
After disabling the extension, the tray doesn't appear in the bottom-left corner like it does by default. I have tried logging out then in but it still doesn't work.

**Comment by phocean** [comment]
Hi,
I don't exactly understand your issue.
The default is normally top right, you don't mention that you changed the settings or use another extension (dash to panel?).
Maybe with a screenshot it would be clearer.

So far I cannot reproduce anything close to your report.

**Comment by phocean** [comment]
After reading again, I think I got what you said.

You are talking about the old default tray of Gnome, which has been deprecated and removed since Gnome 3.26 I believe.

So at first you should check and report here your Gnome version.

Anyway, for a deprecated feature, I would probably not spend a lot of time fixing this.

Closing it for now as I suspect it to be invalid.
