### ISSUE TITLE
Open App left click

### ISSUE THREAD

**Issue by bbedyukh** [phocean/TopIcons-plus#125]
Hi there.

To start, sorry my english, it's so bad.

I've noticed now the Applications added on top bar doesn't open left clicked mouse, before yes. Now, however, left or right clicked mouse does open "notifications" of application. I explain?

![62348177_373116660229007_2947225885868032000_n](https://user-images.githubusercontent.com/44715973/59356031-77bd7e80-8cfe-11e9-888e-73c3275eeeac.jpg)

![64503183_334866240518202_3543168377897877504_n](https://user-images.githubusercontent.com/44715973/59356388-1d70ed80-8cff-11e9-91fb-b233a71d774d.jpg)

Example, before, Skype App. I could open it left mouse click, now to left click mouse, it show me notifications panel. It's the same if I right click mouse.

Thank you!

**Comment by phocean** [comment]
Hi,

Unfortunately, this is something that I cannot fix, because it's application dependent.

There is no specification of what a tray icon should do, like open the window or show the menu.

So, every developer of every app has its own design.

Skype has probably changed between two versions. 

Typically, now I have Skype that opens a menu and Telegram that opens its main window.
