### ISSUE TITLE
icons disappearing after log out, shutdown, reboot dialog cancellation 

### ISSUE THREAD

**Issue by Amunhateb** [phocean/TopIcons-plus#24]
E.g. try to logout pressing "end session" and do not actually ending it. Press cancel in confirm dialog for end session, shutdown, reboot. Icons are disappearing but still clickable. Space for the icons is reserved.

Fedora 23, Gnome 3.18, x86_64. Extension installed from extensions.gnome

**Comment by phocean** [comment]
Thanks for the report, confirmed on my environment.
I will investigate it next week, no time before.

**Comment by phocean** [comment]
Hmm, more checks show that the issue is also there with the legacy tray. I do have an issue with dropbox and keepassx.
What applications are disappearing ?
Please check with TopIcons disabled, to see if it is specific or not to the extension.
If it also happen without TopIcons, then I cannot do anything, the bug should be reported to Gnome.

**Comment by Amunhateb** [comment]
yep. same behaviour with default tray. This is not the extension bug, but gnome 3.18.

**Comment by Amunhateb** [comment]
reported to Gnome bugzilla https://bugzilla.gnome.org/show_bug.cgi?id=767469

**Comment by phocean** [comment]
Cool, I will also follow it there. Thanks!
