### ISSUE TITLE
Add an option to change the 12px outer padding

### ISSUE THREAD

**Issue by AKuederle** [phocean/TopIcons-plus#25]
As some themes modify the default padding between the tray icons, it would be nice, if it would be possible to change the outer padding for this extension as well.

**Comment by phocean** [comment]
Hi,
What theme, for instance ? I need to see how it looks.
I would be rather for a single, global padding between icons, that the user can set. I do not see how the outer padding is actually useful.

**Comment by nevesnunes** [comment]
The idea of outer padding was a hack to make tray icons conform with the appearance of other panel buttons, regardless of the padding between icons. This can be achieved with a global padding setting, but it only works for a single value, since other values will result in outer gaps which are different from the panel button styling.

Another workaround would be to do the same as the panel's status indicators: wrap the boxLayout in a PanelMenu.ButtonBox, which provides the dynamic padding functionality present in panel buttons. The user would control spacing between icons instead of padding, since the outer padding would be fixed by the PanelMenu.ButtonBox style. This way, you have a common appearance between panel widgets, which respects custom theme settings for panel buttons.

If you are interested, I can submit a pull request.

**Comment by AKuederle** [comment]
Thanks for clarifying! I am sry I hadn't time to respond earlier. But it would be really nice to have, as I think this addon is one of the essentials for many people using gnome.

**Comment by phocean** [comment]
Is it not the kind of stuff that'should be handled at the theme level?
I don't get why we should hack the panel for a few pixels when the theme should take care of it (and other panel icons mess with the setting anyway). And the DE itself offers zero option for other parts...

At this moment, I am more concerned by stability issues that I could not track down yet.
So as long as it is not 100% reliable, I am reluctant to add new features: there are already many, compared to what the DE offers..

Am I really alone to have issues on diferent computers?

**Comment by nevesnunes** [comment]
It is indeed appropriate to be handled at the theme level, but TopIcons will only pick up those settings if you use a PanelMenu.ButtonBox style. This feature is more a replacement to the current padding approach, the number of options presented to the user would be the same (you just replace padding with spacing).

**Comment by phocean** [comment]
Ok, then, why not? :-)
Thanks for the explanation.
