### ISSUE TITLE
Add an icon blacklist

### ISSUE THREAD

**Issue by markubiak** [phocean/TopIcons-plus#26]
I would love a way to blacklist specific notification icons.  I don't really care to see that chromium's still running in the background and would love a way to hide the icon.

**Comment by phocean** [comment]
I understand, but it is not the aim of the blacklist in the extension. It is there to address very specific cases, when an extension is redundant with the status icon, as with Skype.

But I don't think it is the job of the extension or even the DE to hide status icons. Because the fact there are hidden does not prevent them from running, doing actions, etc. The user may also forgot that a given application is running, which is a bad thing.

The behavior should be set at the application level.

Regarding Chrome, it seems to be configurable:
https://productforums.google.com/forum/#!topic/chrome/babyOtRtMuw
