### ISSUE TITLE
Blacklist/Whitelist

### ISSUE THREAD

**Issue by topcatzero** [phocean/TopIcons-plus#4]
I have a few applications that I don't particularly care to see in the tray. And they don't give me an option to not show an icon in the tray. It would be nice to be able to specify a list of applications to include/exclude from moving to the top panel.

It would be a bonus to do something similar to [widget blocker](https://extensions.gnome.org/extension/936/widget-blocker/), where I could click on the tray icon I don't want to see on the top panel and add it to the blacklist.

**Comment by phocean** [comment]
Well, I believe this is far beyond the scope of this extension, I am not even sure it is feasible through an extension.
Instead of such a hack, a better approach would be to have a configuration option in the app adding an icon (like most apps do).
Tagged as "won't fix" but if anyone is willing to help and if the implementation is simple, please let me know and feel free to reopen this issue.
If it is complex, then it would be a job better done in a dedicated extension (so that it also works for the standard gnome tray).
