### ISSUE TITLE
Messenger for Desktop tray icon disappears after a while

### ISSUE THREAD

**Issue by isness** [phocean/TopIcons-plus#66]
I'm using Messenger for Desktop (https://messengerfordesktop.com/), but the tray icon disappers after a while when using this extension. This does not happen if I use standard Gnome icons tray. 

I don't know how to debug or add more information, please direct me how to do it if possible :(

**Comment by phocean** [comment]
Hi, I will need to test it. Problem is it is very application dependent. Sometimes a topicons bug, sometimes a bad implementation on the app side, sometimes it is the lack of support in gnome-shell.
To be investigated.

**Comment by zelch** [comment]
Could you please test by modifying ~/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js and adding the following to the top of onTrayIconRemoved:

    if (icons.indexOf(icon) == -1) {
        log("onTrayIconRemoved for invalid icon!");
        return;
    }

I have been doing some debugging today on my pidgin icon disappearing again, and the root cause appears to be that we are getting signals for icons that we are not handling, and the end result is...  Suboptimal.

The gnome-shell code actually has a similar if statement at the top of the icon removal signal handler, leading me to believe that this is a case that the gnome developers found and worked around as well.

Regards,
Zephaniah E. Loss-Cutler-Hull.

**Comment by phocean** [comment]
This was fixed a while ago. Anyway a new issue should be opened if there are other issues with Messenger.
