### ISSUE TITLE
please update the extension on GNOME Shell Extensions website

### ISSUE THREAD

**Issue by jubalh** [phocean/TopIcons-plus#90]
Since the README mentions GNOME Shell Extensions website as the place to get the extension, it would be nice if that could actually be updated timely.
Right now my GNOME 3.26.0 doesnt work with topicons, and I suspect this is because the latest version is not available on the site.
Can  you give some insight on how the process of updating there works so I can understand that?

**Comment by phocean** [comment]
Sorry that it falls on you, but I am tired by such issues.

First, "should", "timely" are no proper terms. I do it in my free time, granted that I have a life, a family and a (very) full time job besides.

I know about updates and I pushed it a week ago to the Gnome website, so go tell it to the Gnome project.
There is almost no one there who cares about the gnome website, so i am fed up with it.

I am considering to drop this extension because the Gnome project makes it a pain in the ass to maintain.

It is too easy that it takes all the complains that only the Gnome project should take.

**Comment by jubalh** [comment]
Maybe you received this issue the wrong way. It is not meant a complain.

It was meant to clear up the process of how the extension comes from your git project to the extensions website.
The "should" and "timely" are quite appropriate especially when I read:

>  If you want or need to continue using status icons, you should feel free to use the TopIcons GNOME Shell extension. This will continue to work and the extension offers a better status icon experience than the current default anyway.
from: https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

I did not want to say that this is your job to do. I opened this to understand how the process works, since its quite obscure from the outside.
Only when I understand that process I can see where and how I myself can offer help.

Since the gnome extensions website has no special contact details I figured I can also get this information from you here.

In the meantime I started to package this application for the distro I use (openSUSE) with the plan to push it into official repos, so that users can have the latest version always from there and don't need to depend on the extensions website.

**Comment by phocean** [comment]
Hi Jubalh,

First, please accept my apologizes for overreacting and misinterpreting your message.

And thanks for contributing.

Nevertheless, I think I am near burn out with work load and this extension altogether.
So, as I explained in issue #91, I will take some distance with it.

Of course, you are welcome to continue the packaging for openSUSE, the extension will not stop working and I may also do some updates from time to time.
I guess my clumsy previous answer gave you the information you needed, somehow.

I am happy you are doing that, because openSUSE is my distro and it is a great distro and community.

**Comment by jubalh** [comment]
Unfortunately the GNOME guys in openSUSE prefer not to have extensions in their repo and in the official distribution because they think extensions break too often.

So I will maintain this in [my repository](https://build.opensuse.org/package/show/home:jubalh/gnome-shell-extension-topicons).
Do you think I should create an PR with instructions on how to add it to the README?
